name: check

on:
  push:
    branches: [ main, main-rc ]
  pull_request:
    branches: [ main ]

jobs:
  check-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v4
      with:
        go-version-file: go.mod

    - name: check
      run: tools/check.go
